### ISSUE TITLE
Possible PRs to {clock}

### ISSUE THREAD

**Issue by trevorld** [trevorld/r-datetimeoffset#26]
* [ ] more generic S3 `calendar_precision()` with an `...` to support `range` argument
* [ ] more generic S3 `calendar_narrow()`

  + Shield `{clock}` internal logic with `inherits(x, "clock_rcrd")`
  + Add `...`?

* [ ] more generic S3 `calendar_widen()`

  + Shield `{clock}` internal logic with `inherits(x, "clock_rcrd")`
  + Add `...` to support setting values other than smallest one

**Comment by trevorld** [comment]
`{clock}`'s unit tests are currently broken making it difficult to develop a PR: https://github.com/r-lib/clock/pull/303

**Comment by trevorld** [comment]
> I think that is going to be the best approach to ensure that long term maintenance of both of our packages are as easy as possible going forward.

It isn't really clear to me why it would be a particularly onerous maintenance obligation if `calendar_widen()` is updated to something like:

```r
calendar_widen <- function(x, precision, ...) {
  if (inherits(x, "clock_calendar")) {
    validate_calendar_widen(x, precision)
  }
  UseMethod("calendar_widen")
}
```

Then `validate_calendar_widen()` could freely do internal `{clock}`-specific validation without interfering with external `calendar_widen()` methods.

> `calendar_narrow()` could maybe become `dto_narrow()`

However, I'm not particularly attached to the names `calendar_precision()`, `calendar_narrow()`, and `calendar_widen()` so I guess I could rename them even though that would lead to proliferation of function names for quite similar concepts...

> Your getter/setters could be `dto_year()`, `dto_set_year()`, etc

I find these really ugly.  I think for now I'll continue to use the really simple generic names like `get_year()` and `set_year()`.  Currently `{clock}` has really simple, clean, extensible S3 generics for these simple datetime accessors that don't need changing but if that changes I could export my own identically named S3 generics.

**Comment by DavisVaughan** [comment]
For one thing, datetimeoffset is not a calendar, as by definition calendar types don't have time zone information. So extending that API at all to work with datetimeoffset is a bit incorrect.

**Comment by trevorld** [comment]
> For one thing, datetimeoffset is not a calendar, as by definition calendar types don't have time zone information.  So extending that API at all to work with datetimeoffset is a bit incorrect.

One could argue `datetimeoffset()` is an alternative "year-month-day" "calendar" with a couple additional optional record fields to enable losslessly storing pdf metadata datetimes but asserting that my metadata datetime object is a "calendar" isn't important to me.  I'll rename `calendar_narrow()`, `calendar_widen()`, and `calendar_precision()` to something else.  I was just trying to make things a little bit easier for users...

**Comment by trevorld** [comment]
`calendar_precision()`, `calendar_narrow()`, and `calendar_widen()` S3 methods have been renamed `datetime_precision()`, `datetime_narrow()`, and `datetime_widen()`.
